import { StyleSheet } from 'react-native';

export const bookingStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F7F9FC' },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 20 },
  hero: { backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingTop: 18, paddingBottom: 14, borderBottomWidth: 1, borderColor: '#E9EDF3' },
  heroEyebrow: { color: '#758197', fontSize: 11, fontWeight: '500' },
  heroTitle: { color: '#18233A', fontSize: 20, fontWeight: '600', marginTop: 4 },
  heroSub: { color: '#62718A', fontSize: 12, marginTop: 4 },
  heroVehicle: { alignSelf: 'flex-start', paddingVertical: 5 },
  sheet: { backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingTop: 18, minHeight: 520 },
  modeTrack: { flexDirection: 'row', backgroundColor: '#F2F5FA', borderRadius: 12, padding: 3 },
  modeButton: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 9 },
  modeActive: { backgroundColor: '#E3EEFF' },
  modeText: { color: '#68778D', fontSize: 13, fontWeight: '500' },
  modeTextActive: { color: '#2158B6', fontWeight: '600' },
  sectionLabel: { color: '#2D394E', fontSize: 13, fontWeight: '500', marginTop: 20, marginBottom: 8 },
  dateField: { borderWidth: 1, borderColor: '#DDE3EC', borderRadius: 11, paddingHorizontal: 14, paddingVertical: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  dateFieldText: { color: '#1E2A41', fontSize: 15, fontWeight: '500' },
  dateFieldIcon: { color: '#2563EB', fontSize: 18 },
  dateRow: { gap: 9, paddingBottom: 2 },
  dateChip: { minWidth: 70, borderWidth: 1, borderColor: '#E0E4ED', backgroundColor: '#FFFFFF', borderRadius: 13, paddingVertical: 10, paddingHorizontal: 10, alignItems: 'center' },
  dateChipActive: { borderColor: '#F26A3D', backgroundColor: '#FFF4EE' },
  dateDay: { color: '#8992A4', fontSize: 10, fontWeight: '700' },
  dateDayActive: { color: '#C24B27' },
  dateNumber: { color: '#19233F', fontSize: 17, fontWeight: '800', marginTop: 2 },
  dateNumberActive: { color: '#C24B27' },
  timeRow: { flexDirection: 'row', gap: 10 },
  timeCard: { flex: 1, borderWidth: 1, borderColor: '#DEE3EC', backgroundColor: '#FFFFFF', borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11 },
  timeCardActive: { borderColor: '#9FC1FA' },
  timeCardLabel: { color: '#8992A4', fontSize: 10, fontWeight: '500' },
  timeCardValue: { color: '#19233F', fontSize: 14, fontWeight: '600', marginTop: 5 },
  timeHelp: { color: '#8490A2', fontSize: 11, marginTop: 8 },
  durationBox: { borderRadius: 11, backgroundColor: '#F7F9FC', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 13, paddingVertical: 10 },
  durationControl: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E1E5ED', alignItems: 'center', justifyContent: 'center' },
  durationControlDisabled: { opacity: 0.38 },
  durationControlText: { color: '#19233F', fontSize: 24, fontWeight: '400', lineHeight: 27 },
  durationValue: { alignItems: 'center' },
  durationMain: { color: '#19233F', fontSize: 19, fontWeight: '600', fontVariant: ['tabular-nums'] },
  durationSub: { color: '#929BAB', fontSize: 10, marginTop: 1 },
  selectionHint: { color: '#758095', fontSize: 12, marginBottom: 10 },
  bestSlot: { backgroundColor: '#F0F6FF', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  bestSlotText: { color: '#25569F', fontSize: 12, fontWeight: '500' },
  bestSlotAction: { color: '#2563EB', fontSize: 12, fontWeight: '600' },
  chargerCard: { borderRadius: 11, borderWidth: 1, borderColor: '#E1E5ED', backgroundColor: '#FFFFFF', marginBottom: 8, overflow: 'hidden' },
  chargerCardSelected: { borderColor: '#93BAF5', backgroundColor: '#F8FBFF' },
  chargerRow: { flexDirection: 'row', alignItems: 'center', padding: 13, gap: 11 },
  radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1.5, borderColor: '#C4CBD8', alignItems: 'center', justifyContent: 'center' },
  radioActive: { borderColor: '#2563EB' },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#2563EB' },
  chargerMain: { flex: 1 },
  chargerName: { color: '#19233F', fontSize: 13, fontWeight: '600' },
  chargerDetail: { color: '#788396', fontSize: 11, marginTop: 3 },
  status: { fontSize: 11, fontWeight: '600' },
  free: { color: '#0A8E66' },
  busy: { color: '#D0692E' },
  suggestionArea: { paddingHorizontal: 14, paddingBottom: 13 },
  suggestionLabel: { color: '#68758A', fontSize: 11, marginBottom: 7 },
  suggestionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  suggestionChip: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8, backgroundColor: '#FFF0E8' },
  suggestionChipActive: { backgroundColor: '#2563EB' },
  suggestionText: { color: '#BC4D24', fontSize: 11, fontWeight: '700' },
  suggestionTextActive: { color: '#FFFFFF' },
  message: { marginTop: 14, color: '#126A51', backgroundColor: '#E8F8F1', borderRadius: 10, padding: 11, fontSize: 12 },
  empty: { color: '#7F8A9D', fontSize: 12, paddingVertical: 14 },
  bookingItem: { borderRadius: 13, borderWidth: 1, borderColor: '#E1E5ED', padding: 12, marginBottom: 9 },
  bookingItemTitle: { color: '#19233F', fontSize: 13, fontWeight: '600' },
  bookingItemTime: { color: '#738095', fontSize: 11, marginTop: 3 },
  cancel: { color: '#C7463D', fontSize: 11, fontWeight: '700', marginTop: 10 },
  demoFootnote: { color: '#9AA3B1', fontSize: 10, lineHeight: 15, marginTop: 18 },
  footer: { backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 12, borderTopWidth: 1, borderColor: '#EBEEF4' },
  primaryButton: { backgroundColor: '#2563EB', borderRadius: 11, alignItems: 'center', paddingVertical: 13 },
  primaryDisabled: { backgroundColor: '#AFC7F4' },
  primaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  footerNote: { color: '#8D98A9', fontSize: 10, textAlign: 'center', marginTop: 7 },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16, 25, 47, 0.48)' },
  pickerSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '70%' },
  pickerHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: '#C8CDD6', alignSelf: 'center', marginBottom: 18 },
  pickerTitle: { color: '#19233F', fontSize: 18, fontWeight: '600' },
  pickerSub: { color: '#8992A4', fontSize: 12, marginTop: 4, marginBottom: 16 },
  pickerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingBottom: 20 },
  pickerChoice: { width: '22%', borderRadius: 9, alignItems: 'center', paddingVertical: 10, backgroundColor: '#F3F5F8' },
  pickerChoiceActive: { backgroundColor: '#2563EB' },
  pickerChoiceText: { color: '#334158', fontSize: 11, fontWeight: '700' },
  pickerChoiceTextActive: { color: '#FFFFFF' },
  dialogOverlay: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(16, 25, 47, 0.48)', padding: 24 },
  dialog: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 20 },
  dialogTitle: { color: '#19233F', fontSize: 18, fontWeight: '600' },
  dialogDetail: { color: '#657187', fontSize: 13, lineHeight: 20, marginTop: 10 },
  dialogNote: { color: '#9A6B53', fontSize: 11, marginTop: 10 },
  dialogActions: { flexDirection: 'row', gap: 9, marginTop: 22 },
  dialogBack: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 10, backgroundColor: '#F0F2F6' },
  dialogBackText: { color: '#354159', fontSize: 13, fontWeight: '600' },
  dialogConfirm: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 10, backgroundColor: '#2563EB' },
});
